PostgreSQL:
  restart: always
  image: postgres
  container_name: postgress_futures
  ports:
    - "5434:5434"
  environment:
    - DEBUG=false
    - POSTGRES_PASSWORD=branch
    - POSTGRES_USER=root
    - POSTGRES_DB=data
    - DB_USER=user
    - DB_PASS=password
    - DB_NAME=
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
  volumes:
    - postgresvol:/var/lib/postgresql/data
